# Generated by Django 3.0 on 2020-09-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0004_auto_20200910_1550'),
        ('votos', '0004_auto_20200910_2253'),
    ]

    operations = [
    ]
