# Generated by Django 3.0 on 2020-09-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimoniales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
