# Generated by Django 3.0 on 2020-09-02 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pais', models.IntegerField()),
                ('pais', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sexo', models.IntegerField()),
                ('sexo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.IntegerField()),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Paises')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
