# Generated by Django 3.0 on 2020-09-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200902_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
