# Generated by Django 3.0 on 2020-09-03 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paises',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sexo',
            name='id',
        ),
        migrations.AlterField(
            model_name='paises',
            name='id_pais',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='id_sexo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.IntegerField()),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Paises')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
