# Generated by Django 3.0 on 2020-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200911_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paises',
            name='pais',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
    ]
