# Generated by Django 3.0 on 2020-09-11 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_auto_20200911_1457'),
        ('votos', '0004_auto_20200910_1550'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilVisitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(null=True)),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Paises')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Sexo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_visitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrupo', models.TextField(max_length=50)),
                ('directo', models.TextField(max_length=200, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='votos.Categoria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_participante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('apellido', models.TextField(max_length=30)),
                ('edad', models.IntegerField(max_length=100)),
                ('dni', models.IntegerField(max_length=10000000)),
                ('domicilio', models.TextField(max_length=1000)),
                ('grupoParticipante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to='perfiles.PerfilParticipante')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Paises')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Sexo')),
            ],
        ),
    ]
