# Generated by Django 3.0 on 2020-09-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
