# Generated by Django 3.0 on 2020-09-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_auto_20200911_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilvisitante',
            name='edad',
        ),
    ]
