# Generated by Django 3.0 on 2020-09-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_perfilvisitante_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilparticipante',
            name='nombreGrupo',
        ),
        migrations.AlterField(
            model_name='participantes',
            name='domicilio',
            field=models.TextField(max_length=500),
        ),
    ]
