# Generated by Django 3.0 on 2020-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_auto_20200912_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='domicilio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
